### ISSUE TITLE
How to access utl through proxy

### ISSUE THREAD

**Issue by sunnybogawat** [pdfcrowd/pdfcrowd-ruby#1]
I want to use API through proxy, Please provide a way how to configure proxy for accessing API. I am using ruby API

**Comment by foxmadr** [comment]
The new API has Proxy support:
[https://pdfcrowd.com/doc/api/html-to-pdf/ruby/#m_set_proxy](https://pdfcrowd.com/doc/api/html-to-pdf/ruby/#m_set_proxy)
